### PR TITLE
Last merging from branch dev to branch main after feedback 

### PR DESCRIPTION
**Pull request by Kana-Fujihira**

### CODE REVIEW

**Review by kna1703 — APPROVED** [review]
good job, well done ! congrats !

**Review by HazeFury — CHANGES_REQUESTED** [review]
"Last merging from branch dev to branch main" until the next 😆

**Comment by kna1703** [comment]
> "Last merging from branch dev to branch main" until the next 😆

last from the last merging from branch dev to branch main until the end of the world

**Review by HazeFury — APPROVED** [review]
impecc 👍 💯

**Pull request merged**
